name: vdf
version: 1.0.1
description: "An encoder and decoder for Valve's KeyValue format (VDF)."
repository: https://github.com/adrianjagielak/vdf-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
