name: vdf
version: 1.1.0
description: "An encoder and decoder for Valve's KeyValue format (VDF) (https://developer.valvesoftware.com/wiki/KeyValues)."
repository: https://github.com/adrianjagielak/vdf-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
